### PR TITLE
Implement and verify data model

### LINKED ISSUE #7: Verify Data Model
# Data Model Implementation and Verification

Doc link : https://github.com/Open-Model-Initiative/OMI-Data-Pipeline/blob/main/modules/odr_datamodel/data_model_overview.md

## Description

Implement and verify the data model for the OMI Data Pipeline. This task includes setting up comprehensive tests for CRUD operations on all entities and ensuring alignment with the documented specifications from the working group meeting notes.

### Data Model Implementation & Verification
- [x] User
- [ ] Team
- [ ] TeamUser
- [x] Content
- [ ] ContentAuthor
- [ ] ContentEmbedding
- [ ] EmbeddingEngine
- [ ] ContentEvents
- [ ] ContentReport
- [ ] ContentSet
- [x] Annotation
- [ ] AnnotationEmbedding
- [ ] AnnotationRating
- [ ] AnnotationReport
- [ ] AnnotationSource

### Test Setup
- [ ] Implement create tests for all entities
- [ ] Implement read tests for all entities
- [ ] Implement update tests for all entities
- [ ] Implement delete tests for all entities

### Documentation Update
- [ ] Update data_model_overview.md with any changes or clarifications
- [ ] Ensure all fields are properly documented, including those added during sandbox process
- [ ] Document any deferred fields or features

## Additional Notes
- Refer to the working group meeting notes for the most up-to-date specifications.
- Ensure that the relationship between Annotations and Content is properly implemented and tested.

### PR DESCRIPTION
**Pull request by robert-cronin**
Fixes #7

### CODE REVIEW

**Comment by robert-cronin** [comment]
I've just added a draft for now including changes so far, I have a couple questions in mind:

- I've noticed there is both permissions and roles, it seems roles is newer. Are we settling on something like role based permissions? if so maybe we can add roles table with permissions to make this extensible in the future? unless there is a clear idea of what roles/permissions will be in which case I guess it makes sense to hardcode it instead
- It seems UserTeam (code) is doing the same thing as TeamUser (spec), I'll just use UserTeam going forward I guess?

cc @fearnworks

**Comment by fearnworks** [comment]
1. I've noticed there is both permissions and roles, it seems roles is newer. Are we settling on something like role based permissions? if so maybe we can add roles table with permissions to make this extensible in the future? unless there is a clear idea of what roles/permissions will be in which case I guess it makes sense to hardcode it instead
RBAC seems fine, but we will need to hash it out first.  

3. It seems UserTeam (code) is doing the same thing as TeamUser (spec), I'll just use UserTeam going forward I guess?
Yea, likely just need to update in the spec doc.

**Comment by robert-cronin** [comment]
> 1. I've noticed there is both permissions and roles, it seems roles is newer. Are we settling on something like role based permissions? if so maybe we can add roles table with permissions to make this extensible in the future? unless there is a clear idea of what roles/permissions will be in which case I guess it makes sense to hardcode it instead
> 
> RBAC seems fine, but will need to discuss with others first.  
> 
> 2. It seems UserTeam (code) is doing the same thing as TeamUser (spec), I'll just use UserTeam going forward I guess?
> 
> Yea, likely just need to update in the spec doc. 

I guess it makes sense for me to update the spec doc as I go, I'll add it to these changes!

**Comment by robert-cronin** [comment]
Some noteworthy changes for reviewers:
- Enums are now defined in a central enums.py file, not sure why there were duplicate definitions, but let me know if we need those.
- Some of the updated_at fields weren't being initialized on create
- Parametrised the embedding dimensions in config.py
- Improved organization of tests
- There is the beginnings of better file organization in modules/odr_core/odr_core/crud/annotation, I think its a great idea but this PR is already quite large so I'll leave that for a later PR

Thank you in advance for your review!

**Comment by robert-cronin** [comment]
code coverage report as I don't think we have a pipeline for that yet. I am getting 86% so far for the odr_core, I think its 80+% is a good target to aim for but let me know if we need to aim higher!

```
---------- coverage: platform linux, python 3.12.5-final-0 -----------
Name                                            Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------------
odr_core/__init__.py                                0      0   100%
odr_core/config.py                                 32      0   100%
odr_core/crud/__init__.py                           0      0   100%
odr_core/crud/annotation/__init__.py                4      0   100%
odr_core/crud/annotation/annotation.py             43     29    33%   13-35, 39, 43, 52-69, 73-79, 85, 97, 109
odr_core/crud/annotation/annotation_rating.py      36      3    92%   34, 58, 75
odr_core/crud/annotation/annotation_report.py      29      1    97%   39
odr_core/crud/annotation/annotation_source.py      37      2    95%   66, 86
odr_core/crud/content.py                          123     42    66%   44, 71, 122, 132, 138-143, 149-163, 176, 180-184, 188, 192, 196-203, 207-212, 237
odr_core/crud/content_event.py                     33      0   100%
odr_core/crud/content_report.py                    30      2    93%   20, 40
odr_core/crud/content_set.py                       48      6    88%   20, 40, 49-51, 63
odr_core/crud/embedding.py                        146     44    70%   37-38, 46-48, 104, 131, 134, 137, 158, 161, 164, 199-209, 213-222, 229, 265-275, 279-288, 295, 312, 322, 328, 338
odr_core/crud/team.py                              45      0   100%
odr_core/crud/user.py                              84     35    58%   46, 51, 55, 71, 82-85, 94, 98-113, 117-122, 126-144
odr_core/database.py                               10      0   100%
odr_core/enums.py                                  38      0   100%
odr_core/models/__init__.py                         6      0   100%
odr_core/models/annotation.py                      62      0   100%
odr_core/models/base.py                             2      0   100%
odr_core/models/content.py                         95      0   100%
odr_core/models/embedding.py                       50      1    98%   44
odr_core/models/team.py                            22      0   100%
odr_core/models/user.py                            39      1    97%   64
odr_core/schemas/__init__.py                        0      0   100%
odr_core/schemas/annotation.py                     93      0   100%
odr_core/schemas/content.py                        95      0   100%
odr_core/schemas/content_report.py                 22      0   100%
odr_core/schemas/content_set.py                    19      0   100%
odr_core/schemas/embedding.py                      65      0   100%
odr_core/schemas/team.py                           21      0   100%
odr_core/schemas/user.py                           40      0   100%
odr_core/utils.py                                  34     34     0%   1-45
-----------------------------------------------------------------------------
TOTAL                                            1403    200    86%
Coverage XML written to file coverage.xml

================================================= 99 passed, 19 warnings in 84.70s (0:01:24) ==================================================
```

**Comment by fearnworks** [comment]
80% is great! Will dig into this review today.

**Review by fearnworks — APPROVED** [review]
Test suite and overall core modules are much cleaner. Great work!

**Comment by fearnworks** [comment]
> Contributor

IRT the new module structure. Definitely agree with splitting these into submodules like you did with annotation going forward. Those initial ones were gettting too long in the tooth

**Pull request merged**
